services:
  app:
    build:
      context: .
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=4096"
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: