version: "3.3"
services:
  arangodb:
    image: arangodb:3.4.3
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1d
  tippecanoe:
    image: klokantech/tippecanoe
    volumes:
      - ./data:/data
