version: "3.3"
services:
  arangodb:
    image: arangodb:3.6.2
    ports:
      - 0:8529
    environment:
      - ARANGO_NO_AUTH=1d
  tippecanoe:
    image: klokantech/tippecanoe
    volumes:
      - ./data:/data
